name: Run Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Install dependencies 
      run: npm i
      
    - name: start wordpress local environment
      run: npx wp-env start --xdebug=coverage

    - name: install phpUnit
      run: npx wp-env run cli --env-cwd=wp-content/plugins/ai-entries composer require phpunit/phpunit  --dev --with-all-dependencies
      
    - name: install phpunit-polyfills
      run: npx wp-env run cli --env-cwd=wp-content/plugins/ai-entries composer require yoast/phpunit-polyfills  --dev --with-all-dependencies
      
    - name: run phpUnit tests
      run: npx wp-env run tests-cli --env-cwd=wp-content/plugins/ai-entries ./vendor/bin/phpunit ./tests --testdox
