name: Run Tests

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: write

jobs:
  
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create Plugin ZIP
        run: ls

      - name: List Directory Contents
        run: ls -R ./ai-entries/  

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: "release-${{ github.sha }}"
          commit_message: ${{ github.event.head_commit.message }} 
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${commit_message}" \
              --generate-notes

      - name: Upload Plugin ZIP
        uses: actions/upload-artifact@v4  
        with:
          name: ai-entries
          path: ./ai-entries/ai-entries.zip  