name: Build release zip

on:
  push:
    branches:
    - release

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@stable
      env:
        SLUG: ai-entries 
